### ISSUE TITLE
initial testing of userspace MR,  build to work on os x

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#191]
first issue for pallavi, good way to get integrated into the project
```
git clone https://github.com/kubernetes-sigs/kpng.git
git remote add jayunit100 git@github.com:jayunit100/kpng.git
git fetch --all
git checkout userspace_backend_linux
./hack/test_e2e.sh -i ipv4 -b userspacelin
```

this will allow you to take on @rajaskakodar s original userspace MR and polish it off :) !

**Comment by jayunit100** [comment]
``` 8668  ./go-mod-tidy-all
 8669  docker build -t kpng:test -f Dockerfile .
 8670* ls
 8671* ./hack/test_e2e.sh -i ipv4 -b userspacelin
```

**Comment by rajaskakodkar** [comment]
Currently, kpng pods are crashing with userspacelin backend (code checked out from https://github.com/kubernetes-sigs/kpng/pull/112) with the following error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1435f22]

goroutine 1 [running]:
sigs.k8s.io/kpng/backends/userspacelin.(*Backend).Setup(0xc0000001a0)
	sigs.k8s.io/kpng/backends/userspacelin@v0.0.0-00010101000000-000000000000/sink.go:124 +0xe2
sigs.k8s.io/kpng/client/localsink/filterreset.(*Sink).Setup(0xc000500000)
	sigs.k8s.io/kpng/client@v0.0.0-20211016172202-2f0db1baddba/localsink/filterreset/filterreset.go:31 +0x22
sigs.k8s.io/kpng/server/jobs/api2local.(*Job).Run(0xc000228510, {0x1abf178, 0xc0004917c0})
	sigs.k8s.io/kpng/server@v0.0.0-00010101000000-000000000000/jobs/api2local/api2local.go:51 +0x3b
main.local2sinkCmd.func1({0x1abfae0, 0xc000228f60})
	sigs.k8s.io/kpng/cmd/kpng/local.go:26 +0x73
sigs.k8s.io/kpng/cmd/kpng/storecmds.LocalCmds.func1(0xc0001af400, {0x1880205, 0x1, 0x1})
	sigs.k8s.io/kpng/cmd/kpng/storecmds/storecmds.go:108 +0x35
github.com/spf13/cobra.(*Command).execute(0xc0001af400, {0xc0002242d0, 0x1, 0x1})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00049b680)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	sigs.k8s.io/kpng/cmd/kpng/main.go:55 +0x125
```

this can be a good start to polish off userspacelin implementation.

**Comment by rajaskakodkar** [comment]
one suggestion from @nehaLohia27, we should try to run this with `-d` flag in e2e_test.sh to make sure this error is caused by e2e tests or not.

**Comment by rajaskakodkar** [comment]
confirmed this by running 
```
/hack/test_e2e.sh -i ipv4 -b userspacelin -d
```
the error still persists so this is not due to any e2e test failure. Userspacelin is crashing.
